### ISSUE TITLE
BUG: Buffer calc for multispoke features

### ISSUE THREAD

**Issue by davepl** [PlummersSoftwareLLC/NightDriverStrip#359]
If you have multiple channels, like the AtomLight project, I think the buffer calculations are wrong.  I think in some cases it takes into account NUM_CHANNELS and in others does not.

Someone needs to go through the code and ideally:
- Make sure the calcs are right and take into account NUM_CHANNELS
- MAX_BUFFERS should be PER CHANNEL and not per system

**Comment by rbergen** [comment]
This looks like something I could sink my teeth into, but I'll have to leave it to someone who has the gear to test (like multiple strips).

**Comment by stretch911** [comment]
I can test on a esp32 wroom mini?

**Comment by rbergen** [comment]
Thanks @stretch911, I appreciate the offer!

However, I am quite unfamiliar with this specific part of the codebase, which for me translates to highly iterative development. That is: make a small change, test to see what happens, conclude it doesn't work, make another change, test again, etc. 

That just doesn't work long-distance, at least for me. But again, thanks for offering to help.

**Comment by davepl** [comment]
Yes, you can code this up with any ESP32 and no LEDs needed.  Just set NUM_CHANNELS to 4 and NUM_LEDS to 144 as an example.

It should do the buffer count calculations based on needing to reserver 4X the memory, but I don't think it does.

**Comment by rbergen** [comment]
@davepl I looked at the code that calculates the number of buffers based on available memory, and then creates the buffer managers. To me, the code looks correct.

The code in question is now contained in `SystemContainer::SetupBufferManagers()`, and: 

- [It calculates the amount of memory required per buffer _and multiplies that with the number of devices that have been defined_, which is NUM_CHANNELS in principle. That gives the amount of memory required for one buffer across all channels.](https://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/21571a8af04ca508018d244f02fa40bed83bcd80/include/systemcontainer.h#L136) 
- [It then divides the amount of available memory (PSRAM if used, regular RAM otherwise) by that number, giving the number of buffers that can be allocated, again for all channels.](https://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/21571a8af04ca508018d244f02fa40bed83bcd80/include/systemcontainer.h#L137)
- [That number of buffers is then compared with MIN_CHANNELS and MAX_CHANNELS, and set to MAX_CHANNELS if greater than it.](https://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/21571a8af04ca508018d244f02fa40bed83bcd80/include/systemcontainer.h#L139-L148)
- [Then, _for each channel_ a LEDBufferManager is created with the calculated number of buffers and the respective GFX device as constructor parameters.](https://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/21571a8af04ca508018d244f02fa40bed83bcd80/include/systemcontainer.h#L154-L155).

(The links in the list point to highlights of the relevant lines in `SystemContainer::SetupBufferManagers()`.)

I think the names of the key variables in the function could be made a bit clearer, and I have a branch ready with alternative names. Beyond that, I wouldn't know what to fix. 

@davepl Unless I've been looking at a different piece of code than you were talking about?
